########## GUIDE ##########
# (1-1) and (1-2) should have the same entry
# (2-1), (2-2), and (2-3) should have the same entry
########## GUIDE ##########
app:
  container:
    image: PLACEHOLDER
    run_time:
      env:
        - name: S3_BUCKET
          value: dataops-poc-deployment # (1-1)
        - name: S3_PREFIX
          value: ml-model-1 # (2-1)
        - name: ROOT_PATH
          value: ml-model-1 # (2-2)
      secrets:
        - name: OPENAPI_KEY
          value: "arn:aws:ssm:eu-central-1:598520881431:parameter/science-dev/poc-deployment/run-rime/openapi_key"
  artifacts:
    s3_bucket: dataops-poc-deployment # (1-2)
    s3_prefix: ml-model-1 # (2-3)
  port_mapping: 
    port: 8080
routing: 
  priority: 10